export interface IFormInputs {
  name: string;
  surname: string;
  patronymic: string;
  birthDate: Date;
  email: string;
  phone: string;
  telegram: boolean;
  viber: boolean;
  livingPlace: string;
  n4: boolean;
  n3: boolean;
  n2: boolean;
  n1: boolean;
  dateOfExam: string;
  education: string;
  visitedJpAsStudent: boolean;
  visitedJpAsTourist: boolean;
  visitedJpOther: boolean;
  didNotVisitJp: boolean;
  visitedJpAdditional: string;
  speakingExpYes: boolean;
  speakingExpNo: boolean;
  speakingExpAdditional: string;
  teachingExp: string;
  workExp: string;
  notebookInternetIsAvailable: string;
  "3-4": boolean;
  "4-5": boolean;
  "5-6": boolean;
  "6-7": boolean;
  weekDaysAvailableYesAlmostAnytime: boolean;
  weekDaysAvailableNoNotAnyDay: boolean;
  weekDaysAvailableYseAnyDayNotAnyHour: boolean;
  weekDaysAvailableAdditional: string;
  vacancyInterest: string;
  workComfort: string;
  skills: string;
  expectations: string;
  motivation: string;
  agreement: boolean;
}

export const defaultValues: IFormInputs = {
  name: "",
  surname: "",
  patronymic: "",
  birthDate: null,
  email: "",
  phone: "",
  telegram: false,
  viber: false,
  livingPlace: "",
  n4: false,
  n3: false,
  n2: false,
  n1: false,
  dateOfExam: "",
  education: "",
  visitedJpAsStudent: false,
  visitedJpAsTourist: false,
  visitedJpOther: false,
  didNotVisitJp: false,
  visitedJpAdditional: "",
  speakingExpYes: false,
  speakingExpNo: false,
  speakingExpAdditional: "",
  teachingExp: "",
  workExp: "",
  notebookInternetIsAvailable: "",
  "3-4": false,
  "4-5": false,
  "5-6": false,
  "6-7": false,
  weekDaysAvailableYesAlmostAnytime: false,
  weekDaysAvailableNoNotAnyDay: false,
  weekDaysAvailableYseAnyDayNotAnyHour: false,
  weekDaysAvailableAdditional: "",
  vacancyInterest: "",
  workComfort: "",
  skills: "",
  expectations: "",
  motivation: "",
  agreement: false,
};
